### ISSUE TITLE
PHATE: Community Hotspots view

### ISSUE THREAD

**Issue by gravesk** [careshub/phate-issue-tracker#1]
- On the Community Hotspots view, select the location (magnifier) option. The system loader fires for a few seconds even though I have entered no value in the location field. This seems an odd behavior. 

- In the location field, enter a zip code (e.g., 40517) and press enter. The selected census tract (504) does not contain the entered zip code (it resolves to 40347). Open the location (magnifier) field again and enter the same zip code and press enter. This time, the selected census tract (41.04) is correct. 

- Select the Data tab. When there is no data to display, there should be a message or indicator to the user that there is nothing to display.

**Comment by gravesk** [comment]
These issues appear in the My Community view as well.

**Comment by ybarnett** [comment]
- The location search form field is independent of the system loader. The tool loads in a number of map layers and various user-associated practice/patient data during the initial process. The system loader got fired for each, thus the flicking effect. I've modified the system loader to stay on the map until all resources are loaded.

- It may be related to initial loading still incomplete. It seems to work fine now. Let me know if the issue still occurs.

- Added a no data sentence. 

Thanks for the comments and testing!

**Comment by gravesk** [comment]
I tried again this morning and the loader never disappears. If I login the system opens the "My Community" view by default. Taking no action, the screen flashes a couple of times as the map is being loaded and the loader is displayed. Waiting 60 seconds, the loader continues to run and it appears to the user that the system isn't ready. I can utilize the other functionality, but at some point the loader should have gone away.

**Comment by gravesk** [comment]
Also, the test scenario of typing in the location bar the zip code 40517 takes me to the wrong census tract the first time. Upon entering it again it takes me to the correct census tract.

**Comment by ybarnett** [comment]
I must have missed some user cases. Do you have access to the demo patient data? Did the service area ever get drawn on the map? I can't reproduce the issue so I am thinking maybe it happens to users who does not have any patient data.

**Comment by gravesk** [comment]
I do have access to the demo patient data, but I am trying to test out all the use cases for the system. So far I am testing with users having no EHR data from the Registry.

**Comment by ybarnett** [comment]
I believe the loader issue is fixed. Please verify. Thanks!

**Comment by gravesk** [comment]
The loader issue is resolved upon first entry. However, if I am on the Hotspots viewer and I select a measure from the menu dropdown (when there's no patient data) the loader fires again and runs for several seconds even though it immediately told me in the menu there was no data.

**Comment by ybarnett** [comment]
Thanks for testing. 

I'm not able to reproduce the Hotspots issue. Could you let me know which measure it was?

**Comment by ybarnett** [comment]
Fixed 1st location search returning incorrect census tract issue --

The address geocoding process returned correct lat/lng coordinates. However, when the map is at national view (small scale), the subsequent 'identify' request with the lat/lng location returned multiple census tracts. 

Solution -- after geocoding, zoom map closer to the lat/lng location, set 'identity' tolerance to 0 to get single census tract.
