### ISSUE TITLE
Production Community HotSpots message

### ISSUE THREAD

**Issue by gravesk** [careshub/phate-issue-tracker#2]
In the production environment, selecting the "Community HotSpots" view launches a message indicating the view is not available. The question in the second half of the message implies that there should be a yes/no option for the user. 

![image](https://user-images.githubusercontent.com/36996308/40249450-07295c56-5aa1-11e8-8ce0-2ef2bd88e2f4.png)

**Comment by ybarnett** [comment]
Message updated to "Click OK to load My Community tool...".

**Comment by ybarnett** [comment]
Changed to a modal dialog.
