### ISSUE TITLE
Selected geography not producing a table result

### ISSUE THREAD

**Issue by gravesk** [careshub/phate-issue-tracker#5]
Bob is reporting that he selects tracts within Connecticut and Virginia and then chooses the data tab and the rows that appear are Virginia and US (no Connecticut). 

![image](https://user-images.githubusercontent.com/36996308/66721612-68e0f880-edd2-11e9-88cd-fe372c2c9edb.png)

![image](https://user-images.githubusercontent.com/36996308/66721617-75fde780-edd2-11e9-91ac-a3190fc8f654.png)

**Comment by ybarnett** [comment]
I have looked into this, but not able to reproduce the issue of census tract values missing under 'DATA' tab. Could you confirm if the issue still persists? And does it happen when loading for an existing practice or when selecting tracts to form a new service area community?

**Comment by gravesk** [comment]
We can close this out. We can't replicate it anymore either.
